[profile.default]
src = "."
out = "out"
libs = ["lib"]
solc_version = "0.8.30"
optimizer = true
optimizer_runs = 200
ignored_error_codes = [6275]
skip = ["lib/openzeppelin-contracts/certora/**"]

[rpc_endpoints]
bsc = "https://bsc-dataseed.binance.org/"
bsc_testnet = "https://data-seed-prebsc-1-s1.binance.org:8545/"

[etherscan]
bsc = { key = "${ETHERSCAN_API_KEY}" }
